# Config file for Server Information
web: Please put your website here 1
admininfo: Please put your website here 2
rulesinfo: To see a list of our server rules go here www.rules.com
owner: [Server Owner Goes Here]
