#==== ServerInformation Configuration (V2.0.0) ====#
web: www.example.com
admininfo: Apply fot admin on our forums at: www.example.com
rulesinfo: To see a list of our server rules go here www.example.com
owner: dsate1
#==== End of Conffiguration (V2.0.0) ====#
